import localFont from "next/font/local";
import {Outfit,Ovo} from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/Components/Footer";

const outfit = Outfit({subsets:["latin"], weight:["400","500","700"]});
const ovo= Ovo({subsets:["latin"],weight:["400"]});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} ${ovo.className}${geistSans.variable} ${geistMono.variable} antialiased`}
      >

       <Toaster/>
       <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
